-- Run ONCE in Supabase -> SQL Editor to enable the contact form.
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  message text
);
alter table public.contact_messages enable row level security;
-- Allow the public anon key to INSERT only (messages stay private; view them in the dashboard).
drop policy if exists "anon insert contact_messages" on public.contact_messages;
create policy "anon insert contact_messages"
  on public.contact_messages for insert to anon with check (true);
